import {
  Sparkles,
  Compass,
  Layers,
  SearchCheck,
  FlaskConical,
  ClipboardList,
  Wrench,
  Target,
  Lightbulb,
  AlertTriangle,
  Info,
  BookOpen,
  GraduationCap,
  Trophy,
  Flame,
  Star,
  CheckCircle2,
  XCircle,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ArrowRight,
  ArrowLeft,
  Menu,
  X,
  Sun,
  Moon,
  Monitor,
  Bookmark,
  BarChart3,
  Repeat,
  Clock,
  Play,
  RotateCcw,
  Quote,
  Bug,
  ShieldCheck,
  Gauge,
  GitBranch,
  Network,
  Boxes,
  ListChecks,
  PencilRuler,
  Microscope,
  Users,
  Home,
  Award,
  Zap,
  Brain,
  Puzzle,
  TrendingUp,
  CircleDot,
  Lock,
  Eye,
} from 'lucide-react'

const MAP = {
  sparkles: Sparkles,
  compass: Compass,
  layers: Layers,
  'search-check': SearchCheck,
  flask: FlaskConical,
  clipboard: ClipboardList,
  wrench: Wrench,
  target: Target,
  lightbulb: Lightbulb,
  warn: AlertTriangle,
  info: Info,
  book: BookOpen,
  cap: GraduationCap,
  trophy: Trophy,
  flame: Flame,
  star: Star,
  check: CheckCircle2,
  x: XCircle,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  'chevron-down': ChevronDown,
  'arrow-right': ArrowRight,
  'arrow-left': ArrowLeft,
  menu: Menu,
  close: X,
  sun: Sun,
  moon: Moon,
  monitor: Monitor,
  bookmark: Bookmark,
  chart: BarChart3,
  repeat: Repeat,
  clock: Clock,
  play: Play,
  reset: RotateCcw,
  quote: Quote,
  bug: Bug,
  shield: ShieldCheck,
  gauge: Gauge,
  branch: GitBranch,
  network: Network,
  boxes: Boxes,
  checks: ListChecks,
  ruler: PencilRuler,
  microscope: Microscope,
  users: Users,
  home: Home,
  award: Award,
  zap: Zap,
  brain: Brain,
  puzzle: Puzzle,
  trending: TrendingUp,
  dot: CircleDot,
  lock: Lock,
  eye: Eye,
}

export default function Icon({ name, className, size = 20, strokeWidth = 2, ...rest }) {
  const C = MAP[name] || Sparkles
  return <C className={className} size={size} strokeWidth={strokeWidth} {...rest} />
}

export const ICON_NAMES = Object.keys(MAP)
